### ISSUE TITLE
type Prism

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [monadfix/microlens#135]
In Lens.Micro there is a Prism section that explains how Prisms are just Traversals. It may just be easier to define a type alias for Prism with the chosen microlens definition.

`type Prism = Traversal`

**Comment by neongreen** [comment]
We want microlens to be lens-compatible. If I export a `Prism s t a b` from a library that uses microlens, and it turns out that it can't be used as a prism in a `lens`-using codebase — this would lead to a lot of head-scratching.

`microlens` is not trying to have its own ecosystem. It must play nicely with `lens`.

**Comment by BebeSparkelSparkel** [comment]
Thanks
